AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - "Gemfile.lock"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
