name: Continuous Integration

on: [pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get ruby version
        id: ruby_version
        run: echo "##[set-output name=RUBY_VERSION;]$(cat .ruby-version | cut -c1-3)"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '${{ steps.ruby_version.outputs.RUBY_VERSION }}'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bundle exec rubocop

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get ruby version
        id: ruby_version
        run: echo "##[set-output name=RUBY_VERSION;]$(cat .ruby-version | cut -c1-3)"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '${{ steps.ruby_version.outputs.RUBY_VERSION }}'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec
