name: 'Continuous Integration: Ruby'

on: [pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        name: Install Ruby + Dependencies
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        name: Install Ruby + Dependencies
        with:
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
