name: 'Continuous Integration: Ruby'

on: [pull_request]

defaults:
  run:
    working-directory: ruby

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        name: Install Ruby + Dependencies
        with:
          working-directory: ruby
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        name: Install Ruby + Dependencies
        with:
          working-directory: ruby
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
